[package]
name = "tazmondo/tev"
version = "1.0.6"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
exclude = ["**"]
include = [
	"default.project.json",
	"lib",
	"lib/**",
	"wally.toml",
	"README.md",
]

[dependencies]
Future = "tazmondo/future@2.0.2"
Guard = "red-blox/guard@1.0.0"